<?php

namespace App\Services\CustomLutBuilds;

use App\Color\CubeSize;
use App\Color\LutTransformV1;
use App\Color\NormalizedRgb;
use App\ValueObjects\LutTransformParameters;
use Illuminate\Support\Facades\File;
use RuntimeException;

class WriteCubeFile
{
    public function __construct(private readonly LutTransformV1 $transform) {}

    public function handle(string $path, CubeSize $size, PackageName $packageName, LutTransformParameters $parameters, string $parametersHash): void
    {
        File::ensureDirectoryExists(dirname($path));

        $temporaryPath = $path.'.tmp-'.bin2hex(random_bytes(6));
        $stream = fopen($temporaryPath, 'wb');

        if ($stream === false) {
            throw new RuntimeException('Unable to create temporary CUBE file.');
        }

        try {
            $this->writeHeader($stream, $size, $packageName, $parametersHash);
            $lastIndex = $size->value - 1;

            for ($blueIndex = 0; $blueIndex < $size->value; $blueIndex++) {
                $blue = $blueIndex / $lastIndex;

                for ($greenIndex = 0; $greenIndex < $size->value; $greenIndex++) {
                    $green = $greenIndex / $lastIndex;

                    for ($redIndex = 0; $redIndex < $size->value; $redIndex++) {
                        $red = $redIndex / $lastIndex;
                        $result = $this->transform->transform(new NormalizedRgb($red, $green, $blue), $parameters);
                        fwrite($stream, $this->format($result->red).' '.$this->format($result->green).' '.$this->format($result->blue)."\n");
                    }
                }
            }

            fflush($stream);
        } finally {
            fclose($stream);
        }

        if (! rename($temporaryPath, $path)) {
            @unlink($temporaryPath);

            throw new RuntimeException('Unable to finalize CUBE file.');
        }
    }

    /**
     * @param  resource  $stream
     */
    private function writeHeader(mixed $stream, CubeSize $size, PackageName $packageName, string $parametersHash): void
    {
        $minimum = $this->format((float) config('custom-lut-builds.cube_domain_minimum', 0.0));
        $maximum = $this->format((float) config('custom-lut-builds.cube_domain_maximum', 1.0));

        fwrite($stream, "# Generated by LUT Web\n");
        fwrite($stream, '# Transform: '.config('custom-lut-builds.transform_version')."\n");
        fwrite($stream, '# Generator: '.config('custom-lut-builds.generator_version')."\n");
        fwrite($stream, '# Parameters SHA-256: '.$parametersHash."\n");
        fwrite($stream, 'TITLE "'.$packageName->title()."\"\n");
        fwrite($stream, 'LUT_3D_SIZE '.$size->value."\n");
        fwrite($stream, 'DOMAIN_MIN '.$minimum.' '.$minimum.' '.$minimum."\n");
        fwrite($stream, 'DOMAIN_MAX '.$maximum.' '.$maximum.' '.$maximum."\n\n");
    }

    private function format(float $value): string
    {
        if (! is_finite($value)) {
            throw new RuntimeException('Cannot serialize a non-finite CUBE value.');
        }

        $value = min(1.0, max(0.0, $value));

        if (abs($value) < 0.5 * (10 ** -((int) config('custom-lut-builds.cube_precision', 9)))) {
            $value = 0.0;
        }

        return number_format($value, (int) config('custom-lut-builds.cube_precision', 9), '.', '');
    }
}
