<?php

namespace App\Support\Storefront;

use Illuminate\Support\Str;

final class FaqCatalog
{
    /**
     * @return list<array{
     *     slug: string,
     *     title: string,
     *     description: string,
     *     items: list<array{id: string, question: string, answer: string, keywords: list<string>}>
     * }>
     */
    public function sections(): array
    {
        return [
            $this->section('getting-started', 'Getting started', 'The essentials for understanding, choosing, and receiving a LUT.', [
                ['What is a LUT?', 'A LUT, or lookup table, remaps input color values to new output values. It gives photographs or video a repeatable creative color treatment without permanently changing the original media.', ['basics', 'lookup table', 'color']],
                ['What does a creative LUT change?', 'A creative LUT can shape contrast, color balance, saturation, highlight and shadow character, and split-toning. It does not repair focus, motion blur, clipping, or badly recorded source footage.', ['creative', 'contrast', 'color']],
                ['Is a LUT the same as a preset?', 'Not exactly. A LUT applies a color transformation, while a preset may also change application-specific controls such as exposure, curves, grain, sharpening, masks, or camera profiles.', ['preset', 'difference', 'settings']],
                ['Can beginners use these LUTs?', 'Yes. Start with the 33-point CUBE file, apply it in your editor, and reduce the LUT mix if needed. The product preview and tester help you choose before building a full edit.', ['beginner', 'first use', 'cube33']],
                ['Are these LUTs for photos, videos, or both?', 'The CUBE format can be used for both photos and videos in compatible applications. Results depend on the source color space, exposure, white balance, and the controls available in your editor.', ['photo', 'video', 'both']],
                ['What should I prepare before applying a LUT?', 'Correct obvious exposure and white-balance problems first, confirm the intended color space, and keep a clean copy of the original. A technically sound starting image produces more predictable color.', ['prepare', 'exposure', 'white balance']],
                ['How do I know whether a LUT is available now?', 'The product page shows its current purchase status. A ready product lists package contents and an active purchase or claim action; an unavailable message means checkout is intentionally blocked.', ['availability', 'ready', 'purchase']],
                ['What is included with an individual LUT?', 'A ready individual release includes 17-point, 33-point, and 65-point CUBE files, a customer README, a manifest, checksums, and a ZIP package delivered through your account.', ['included', 'contents', 'zip']],
                ['Do I need an account to buy or test a LUT?', 'Yes. A verified account protects downloads, purchase history, and private photo tests. Browsing products and reading the FAQ remain available without signing in.', ['account', 'verified', 'guest']],
                ['Where can I get personal help?', 'Email goleaf@gmail.com with the product name, your account email, and a concise description of the issue. Never send passwords, complete payment credentials, or confidential source files.', ['support', 'email', 'help']],
            ]),
            $this->section('choosing-a-lut', 'Choosing a LUT', 'How previews, categories, tags, and intensity help you find the right look.', [
                ['How should I choose between similar LUTs?', 'Compare the dedicated preview scene, description, category, and tags, then use Try on Your Photo when available. Prioritize skin, highlight, and shadow behavior over a single favorite color.', ['choose', 'compare', 'preview']],
                ['Why does every LUT use a different preview image?', 'Distinct preview scenes demonstrate the catalog across varied subjects and lighting instead of repeating one photograph. Your own image remains the best final compatibility check.', ['unique image', 'demo', 'scene']],
                ['Can preview images guarantee the same result on my work?', 'No. Previews demonstrate the look on a particular source image. Camera response, lighting, color space, exposure, display calibration, and application interpolation can all change the result.', ['preview', 'guarantee', 'result']],
                ['What do the category labels mean?', 'Categories describe likely starting uses such as cinematic, portrait, travel, street, wedding, warm, cool, moody, vintage, or pastel. They are recommendations rather than technical restrictions.', ['category', 'style', 'use']],
                ['What do product tags tell me?', 'Tags summarize practical uses and color traits, including lighting, subject, contrast, black level, highlight handling, palette, finish, and overall grade strength.', ['tags', 'traits', 'filter']],
                ['What is a bold grade?', 'A bold grade makes a clearly visible creative change across several color and tonal controls. Reduce the LUT mix when you want its palette with a gentler overall effect.', ['bold', 'strength', 'mix']],
                ['What is a balanced grade?', 'A balanced grade has an obvious look while retaining a flexible starting point for finishing. It is often suitable when you want visible character without the strongest catalog response.', ['balanced', 'strength', 'look']],
                ['What is a subtle grade?', 'A subtle grade favors restrained changes and is useful when source color is already close to the desired result. Even subtle LUTs may need a lower mix on sensitive footage.', ['subtle', 'strength', 'gentle']],
                ['Which LUTs are best for skin tones?', 'Start with products tagged For Portraits, Skin Friendly, Soft Highlights, or Editorial, then test with a representative portrait. Always check varied complexions under the real delivery lighting.', ['skin', 'portrait', 'people']],
                ['Which LUTs work for night or mixed lighting?', 'Start with products tagged For Night, Cinematic, Deep Blacks, Protected Highlights, or Cool. Mixed sources may still require shot-level white balance and selective corrections.', ['night', 'mixed light', 'cinematic']],
            ]),
            $this->section('formats-and-compatibility', 'Formats and compatibility', 'CUBE sizes, supported software, devices, and interchange details.', [
                ['Which file format is delivered?', 'Storefront LUT products are delivered as standard three-dimensional .cube files inside a ZIP package. The package supplies three sampling sizes for broad application compatibility.', ['cube', 'format', 'file']],
                ['Why are there 17-point, 33-point, and 65-point files?', 'The sizes describe the three-dimensional sampling lattice. Smaller files are lighter and widely compatible; larger files provide denser samples when the host application supports them.', ['17', '33', '65']],
                ['Which CUBE size should I try first?', 'Use the 33-point CUBE first because it offers a practical balance of fidelity, size, and compatibility. Switch to 17 or 65 only when your application or workflow benefits from it.', ['cube33', 'recommended', 'size']],
                ['When should I use the 17-point CUBE?', 'Choose the 17-point file for lightweight previews, older hosts, or workflows that impose a smaller lattice limit. Compare it against Cube33 before final delivery when possible.', ['cube17', 'lightweight', 'older']],
                ['When should I use the 65-point CUBE?', 'Choose the 65-point file when your host explicitly supports it and you want denser sampling for final work. It consumes more storage and may not look meaningfully different in every application.', ['cube65', 'high resolution', 'final']],
                ['Does the LUT work in Adobe Premiere Pro?', 'Premiere Pro supports CUBE LUT workflows through Lumetri Color. Import the chosen CUBE as a creative look or through the appropriate technical slot for your managed workflow.', ['premiere pro', 'adobe', 'lumetri']],
                ['Does the LUT work in DaVinci Resolve?', 'DaVinci Resolve supports CUBE files. Place or import the LUT through Resolve preferences, refresh the LUT list, and apply it at the appropriate node in your color pipeline.', ['davinci resolve', 'blackmagic', 'node']],
                ['Does the LUT work in Final Cut Pro?', 'Final Cut Pro supports custom LUT effects and CUBE files. Apply the Custom LUT effect, choose the file, confirm input and output handling, and adjust mix as needed.', ['final cut pro', 'apple', 'custom lut']],
                ['Does the LUT work in Photoshop or Affinity Photo?', 'Both can use CUBE color lookups through their supported adjustment workflows. Confirm that your document is in a compatible RGB mode and keep the adjustment editable.', ['photoshop', 'affinity photo', 'photo']],
                ['Can I use these LUTs on a phone or tablet?', 'Only if the mobile application supports importing standard CUBE files. Mobile operating systems do not apply CUBE files globally, so verify import support in the specific editor first.', ['mobile', 'phone', 'tablet']],
            ]),
            $this->section('installation', 'Installation', 'Importing and organizing the delivered files in common editing applications.', [
                ['How do I open the downloaded package?', 'Download the ZIP from My LUTs, keep the original as a backup, and extract it with your operating system. The CUBE directory contains all three usable LUT sizes.', ['extract', 'zip', 'open']],
                ['Do I need to install all three CUBE sizes?', 'No. Most customers can install only the 33-point file and retain the others in the ZIP. Install additional sizes when a particular application requests or benefits from them.', ['install', 'all sizes', 'cube33']],
                ['Where should I store my LUT files?', 'Use a backed-up folder with stable names and organize by vendor or project. If an editor copies LUTs into its own library, also keep the original downloaded ZIP separately.', ['organize', 'folder', 'backup']],
                ['How do I install a LUT in Premiere Pro?', 'Open Lumetri Color, use the Browse option in the suitable LUT selector, and choose the CUBE file. For permanent menu installation, follow the current Adobe shared-LUT folder guidance.', ['premiere install', 'lumetri', 'browse']],
                ['How do I install a LUT in DaVinci Resolve?', 'Open Project Settings or Preferences, reveal the LUT folder or use the import control, add the CUBE file, and refresh the list before applying it to a node.', ['resolve install', 'refresh', 'folder']],
                ['How do I install a LUT in Final Cut Pro?', 'Add the Custom LUT effect to the clip, open its LUT menu, choose a custom CUBE file, and confirm the conversion settings. Save an effect preset if you reuse the setup.', ['final cut install', 'effect', 'custom']],
                ['How do I load a LUT in Photoshop?', 'Add a Color Lookup adjustment layer, select Load 3D LUT, and choose the CUBE file. Using an adjustment layer keeps the look editable and easy to mask or reduce.', ['photoshop install', 'color lookup', 'layer']],
                ['How do I load a LUT in Affinity Photo?', 'Add a LUT adjustment, import the CUBE file, and keep the adjustment live when possible. Use layer opacity or blend controls to tune the strength non-destructively.', ['affinity install', 'adjustment', 'opacity']],
                ['Why does my application not show the new LUT?', 'Confirm the file was extracted, uses the .cube extension, and is stored in the correct application folder. Restart or refresh the LUT list because many editors cache it.', ['missing', 'refresh', 'restart']],
                ['Can I rename the CUBE files?', 'Usually yes, but keeping the delivered name makes support and version identification easier. Do not edit the file contents unless you understand the CUBE specification and licensing limits.', ['rename', 'filename', 'support']],
            ]),
            $this->section('using-luts', 'Using LUTs', 'Practical placement, intensity, corrections, and consistency advice.', [
                ['At what point in the edit should I apply a creative LUT?', 'Normalize camera color, set exposure and white balance, then apply the creative LUT before final shot matching and selective polish. Exact node or layer order depends on the host.', ['order', 'workflow', 'creative']],
                ['Should I adjust exposure before or after the LUT?', 'Make large technical exposure corrections before the LUT so it receives a predictable signal. Small creative refinements can be made afterward while watching highlight and shadow detail.', ['exposure', 'before', 'after']],
                ['How do I reduce LUT strength?', 'Use the host application’s mix, opacity, key output, or blend control. Start near fifty percent on difficult source material and increase until the look supports the image.', ['strength', 'opacity', 'mix']],
                ['Can I combine more than one LUT?', 'You can, but stacked nonlinear transforms may clip or distort color quickly. Use a clear purpose for each LUT, reduce their strengths, and monitor scopes between operations.', ['combine', 'stack', 'multiple']],
                ['Can I make additional color corrections after applying a LUT?', 'Yes. LUTs are starting transforms, not locked final grades. Continue with shot matching, skin isolation, curves, saturation control, grain, sharpening, and delivery adjustments as needed.', ['adjust', 'after', 'grade']],
                ['Why are my highlights clipping after the LUT?', 'The source may already be near the display limit or an earlier conversion may be too aggressive. Lower exposure or gain before the LUT, reduce its mix, and inspect the color-space pipeline.', ['highlights', 'clipping', 'gain']],
                ['Why are my shadows too dark?', 'Raise shadow or lift controls before the LUT, reduce the LUT mix, or choose a product tagged Open Shadows or Lifted Blacks. Verify the display and output range are configured correctly.', ['shadows', 'dark', 'lift']],
                ['How can I keep skin tones natural?', 'Balance exposure and white balance first, reduce the LUT mix, and use a secondary correction if needed. Evaluate skin on a calibrated display rather than relying only on vectorscope targets.', ['skin', 'natural', 'secondary']],
                ['How do I match several shots with one LUT?', 'Correct each shot into a consistent technical baseline before applying the shared LUT. Afterward, trim exposure, balance, and saturation per shot while preserving the common creative palette.', ['match', 'shots', 'consistency']],
                ['Can I bake a LUT into exported media?', 'Yes, when the chosen application and license allow the normal rendered result. Confirm export color space and levels, then review the rendered file on the target delivery display.', ['export', 'render', 'bake']],
            ]),
            $this->section('color-management', 'Color management', 'Log footage, display-referred looks, HDR, scopes, and monitor considerations.', [
                ['Are these camera Log conversion LUTs?', 'No. Storefront products are display-referred creative RGB looks, not camera-specific technical conversions. Convert Log or wide-gamut footage into the intended working space before applying them.', ['log', 'technical', 'conversion']],
                ['Can I apply a creative LUT directly to Log footage?', 'Direct application may produce flat, clipped, or unexpected color because the LUT expects a display-referred signal. Apply the correct camera or managed color-space conversion first.', ['log footage', 'direct', 'color space']],
                ['Which working color space should I use?', 'Use the color-managed space required by your project and application, then place the creative LUT where it receives a compatible display-referred RGB signal. Test the exact pipeline before batch work.', ['working space', 'managed', 'rgb']],
                ['Do the LUTs support Rec.709 workflows?', 'They are designed as display-referred creative looks and are suitable starting points for common SDR workflows when applied in the correct place. Always verify levels and gamut for final Rec.709 delivery.', ['rec709', 'sdr', 'delivery']],
                ['Can I use these LUTs in HDR projects?', 'They are not authored as HDR technical transforms. You may use them inside a managed pipeline that safely maps their display-referred creative response, but careful scope and highlight review is essential.', ['hdr', 'wide gamut', 'scope']],
                ['Why does the LUT look different between applications?', 'Hosts may use different interpolation, color management, input ranges, bit depths, or display transforms. Match project settings and compare exported results rather than assuming identical previews.', ['different apps', 'interpolation', 'render']],
                ['Does monitor calibration matter?', 'Yes. An uncalibrated display can hide casts, crushed shadows, or clipped highlights. Calibration does not change the LUT file, but it improves the reliability of your grading decisions.', ['monitor', 'calibration', 'display']],
                ['Should I use video scopes with a LUT?', 'Yes. Waveform, parade, vectorscope, and gamut warnings reveal problems that may be difficult to see. Use scopes together with visual judgment and the intended delivery requirements.', ['scopes', 'waveform', 'vectorscope']],
                ['What does interpolation mean for a CUBE LUT?', 'Interpolation estimates colors between stored lattice points. Trilinear and tetrahedral methods can differ slightly, especially with strong transforms, which is one reason host applications may not match exactly.', ['interpolation', 'tetrahedral', 'trilinear']],
                ['Will a higher CUBE size fix an incorrect color pipeline?', 'No. A 65-point lattice samples the same intended transform more densely, but it cannot correct wrong input color space, range, white balance, exposure, or display management.', ['higher size', 'pipeline', 'fix']],
            ]),
            $this->section('photo-tester', 'Try on Your Photo', 'Eligibility, upload limits, privacy, processing, and comparison behavior.', [
                ['What does Try on Your Photo do?', 'It lets a verified user upload a supported image, applies the selected product’s private Cube33 release, and returns watermarked before and after previews for a temporary comparison.', ['tester', 'upload', 'before after']],
                ['Why is the Try on Your Photo button missing?', 'The button appears only for published, testable individual LUTs with a current ready private CUBE release. Bundles, incomplete packages, and unavailable products intentionally omit it.', ['missing button', 'eligibility', 'ready']],
                ['Why must I verify my email before testing?', 'Verification reduces automated abuse and ties temporary private files to the correct account. It also enables secure access checks for preview images and later deletion.', ['verify', 'email', 'security']],
                ['Which image formats can I upload?', 'The tester accepts valid JPEG, PNG, and supported WebP raster images within configured size and dimension limits. Renaming another file type to a permitted extension will not bypass validation.', ['jpeg', 'png', 'webp']],
                ['Are SVG or GIF uploads supported?', 'No. SVG and GIF uploads are rejected because the tester is designed for still raster photographs with a controlled decode and color-processing pipeline.', ['svg', 'gif', 'unsupported']],
                ['Will the tester use my original filename for storage?', 'No. The service generates private randomized paths and keeps only a sanitized display name. This prevents path traversal and reduces accidental disclosure of customer filenames.', ['filename', 'random', 'security']],
                ['Are tester previews watermarked?', 'Yes. The temporary before and after outputs are watermarked and intended only for evaluating a product. Purchased CUBE files do not contain an image watermark.', ['watermark', 'preview', 'purchase']],
                ['How long are tester files kept?', 'Each test receives an automatic expiration time shown in the interface. Expired tests can no longer serve signed previews and are removed by the cleanup process.', ['expiration', 'temporary', 'cleanup']],
                ['Can another customer view my tester images?', 'No. Preview routes require the owning verified account and a valid temporary signature. Requests from a different account or with an invalid signature are rejected.', ['private', 'owner', 'signed']],
                ['What should I do if a photo test fails?', 'Try a valid smaller JPEG or PNG, confirm the product still shows the tester button, and retry once. If it continues, email support with the product name and time of the attempt.', ['failed', 'retry', 'support']],
            ]),
            $this->section('downloads-and-account', 'Downloads and account', 'Where releases appear, how access works, and what to keep for recovery.', [
                ['Where do purchased LUTs appear?', 'Completed products appear in My LUTs for the purchasing account. The account page provides controlled downloads without exposing private storage paths or internal filenames.', ['my luts', 'library', 'account']],
                ['When does a paid download become available?', 'Access is granted after the server verifies a completed payment and marks fulfillment ready. A browser approval alone does not grant the package until capture validation succeeds.', ['paid', 'available', 'capture']],
                ['How are free LUTs delivered?', 'A ready free product can be claimed from checkout after account verification and required legal consent. It then appears in My LUTs without a PayPal payment.', ['free', 'claim', 'delivery']],
                ['Can I download the ZIP more than once?', 'Active entitlements are designed to remain available from the account library, subject to applicable terms and security limits. Keep a local backup after the first successful download.', ['redownload', 'multiple', 'backup']],
                ['Why did a download return Not Found?', 'The entitlement may belong to another account, the order may not be fulfilled, the release may be unavailable, or the secure path check may have failed. Sign into the purchasing account first.', ['404', 'not found', 'entitlement']],
                ['Can I share a download link?', 'No. Account download links are access-controlled and may be temporary. Sharing credentials, links, ZIP packages, or extracted LUT files violates security expectations and may violate the license.', ['share link', 'access', 'license']],
                ['Should I keep the original ZIP?', 'Yes. Keep the original ZIP and its manifest and checksums together. It provides the cleanest backup and makes the exact product release easier to identify during support.', ['original zip', 'backup', 'manifest']],
                ['What are manifest.json and CHECKSUMS.txt for?', 'The manifest identifies the release and included files, while CHECKSUMS.txt records SHA-256 hashes. Advanced users can use them to confirm file integrity after transfer or backup.', ['manifest', 'checksums', 'sha256']],
                ['Can I move my purchase to another account?', 'Account transfers are not automatic because payment, consent, and entitlement records are tied to the original purchaser. Contact support before creating duplicate purchases.', ['transfer', 'account', 'purchase']],
                ['What information should I include in a download support request?', 'Include your account email, product name, approximate purchase time, and the visible error. Do not attach credentials, payment secrets, or the licensed LUT package itself.', ['download support', 'details', 'email']],
            ]),
            $this->section('paypal-and-checkout', 'PayPal and checkout', 'Payment availability, verification, currency, captures, and safe retry behavior.', [
                ['How are paid LUTs purchased?', 'When checkout is enabled and ready, sign into a verified account, review the single product and legal consents, and approve payment through the PayPal checkout shown on the site.', ['paypal', 'purchase', 'checkout']],
                ['Do I need a PayPal account?', 'PayPal may offer account or eligible guest payment methods depending on country, device, and PayPal policy. The available choices are displayed by PayPal during approval.', ['paypal account', 'guest', 'card']],
                ['Which currency is used?', 'Storefront catalog prices and PayPal order snapshots use EUR. Your funding source may perform currency conversion under terms and rates shown by PayPal or your financial institution.', ['eur', 'currency', 'conversion']],
                ['Why does a product say PayPal checkout is unavailable?', 'Checkout fails closed when payment credentials, merchant identity, tax readiness, legal versions, package readiness, or live-payment authorization are incomplete. Try again only after the status changes.', ['unavailable', 'readiness', 'blocked']],
                ['Can the displayed price change during PayPal approval?', 'The server creates an order from the current product price and validates the captured amount and currency. If product terms change before completion, restart checkout for a fresh snapshot.', ['price', 'snapshot', 'amount']],
                ['What happens after I approve PayPal?', 'The server captures and validates the PayPal order, records the payment result, fulfills the order, and creates an entitlement. The package appears only after those server-side checks pass.', ['approve', 'capture', 'fulfill']],
                ['What if PayPal approval succeeds but the site still shows pending?', 'Do not repeatedly create new orders. Refresh your account order page, allow a short processing interval, and contact support with the order time if the status remains pending.', ['pending', 'approval', 'retry']],
                ['How does the site prevent duplicate PayPal orders?', 'Checkout uses idempotency identifiers and validates ownership and state before fulfillment. Repeating the same supported request should not create multiple entitlements for one completed order.', ['duplicate', 'idempotency', 'order']],
                ['Does the site store my complete card number?', 'No. Card or PayPal funding details are handled by PayPal’s checkout surface. The application stores the order, payment status, identifiers, amount, currency, and required audit records.', ['card', 'stored', 'privacy']],
                ['Where can I read the checkout terms?', 'Links to the Terms of Sale, License Agreement, Refund Policy, and digital-delivery consent are shown during checkout. Read the current versions before approving payment.', ['terms', 'license', 'refund']],
            ]),
            $this->section('licensing', 'Licensing and commercial use', 'Permitted creative output, prohibited redistribution, teams, clients, and records.', [
                ['Can I use a purchased LUT for commercial client work?', 'Yes, normal rendered creative work is permitted under the License Agreement accepted at purchase. Review the current agreement for exact scope, restrictions, and account responsibilities.', ['commercial', 'client', 'use']],
                ['Can I use the LUT on personal projects?', 'Yes. Personal photo and video projects are a normal use of the licensed files, provided you follow the License Agreement and do not redistribute the LUT itself.', ['personal', 'project', 'license']],
                ['Can I deliver graded photos or videos to clients?', 'Yes. You may deliver rendered creative output that uses the LUT as part of the edit. Do not include the reusable CUBE file or package unless separately authorized.', ['deliver', 'rendered', 'client']],
                ['Can I send the CUBE file to a client or collaborator?', 'Not by default. Sharing the reusable file is redistribution even when connected to a project. Use rendered output or ensure every person who needs the file has proper authorization.', ['share cube', 'collaborator', 'redistribution']],
                ['Can I resell or give away the LUT?', 'No. Reselling, uploading, gifting, publishing, sublicensing, or otherwise distributing the CUBE files or ZIP package is prohibited unless written permission explicitly allows it.', ['resell', 'giveaway', 'prohibited']],
                ['Can I include the LUT in a project template?', 'Only when the template does not distribute or expose the reusable LUT file and the license permits the intended use. A template containing the CUBE itself is redistribution.', ['template', 'include', 'project']],
                ['Can a whole company use one purchase?', 'Do not assume one personal purchase covers an organization or unlimited users. Review the License Agreement and contact support for team, studio, education, or enterprise requirements.', ['company', 'team', 'studio']],
                ['Can I modify the LUT for my own workflow?', 'You may adjust the look through normal editing controls for licensed creative use. Distribution of modified or converted reusable LUT files remains restricted by the License Agreement.', ['modify', 'convert', 'derivative']],
                ['Do I need to credit LUT Web in finished work?', 'Standard rendered use generally does not require visible credit unless a specific promotion or agreement says otherwise. Keeping internal purchase records is still recommended.', ['credit', 'attribution', 'finished']],
                ['Which license version applies to my order?', 'The checkout records the license version accepted with the order. Keep the order and package records, and consult that captured agreement when determining rights for an earlier purchase.', ['license version', 'order', 'record']],
            ]),
            $this->section('troubleshooting', 'Troubleshooting', 'Common import, visual, archive, and integrity problems and their likely causes.', [
                ['Why does the LUT make my image look too strong?', 'The source may already contain a strong grade or different contrast range. Lower the LUT mix, correct exposure and white balance first, or choose a softer tagged product.', ['too strong', 'mix', 'source']],
                ['Why does the LUT add an unexpected color cast?', 'A mismatched white balance, color space, Log conversion, or display transform can shift the intended palette. Neutralize the technical pipeline before judging the creative result.', ['cast', 'white balance', 'unexpected']],
                ['Why are colors banding after I apply a LUT?', 'Low bit depth, heavy compression, extreme corrections, or repeated transforms can reveal banding. Work in a higher-precision pipeline, reduce transform strength, and avoid unnecessary re-encoding.', ['banding', 'bit depth', 'compression']],
                ['Why can I not unzip the package?', 'Confirm the download completed, has a .zip extension, and matches the expected file size. Download it again from My LUTs rather than using a partial browser cache or renamed file.', ['unzip', 'corrupt', 'partial']],
                ['How can I verify a downloaded file?', 'Use a SHA-256 utility to compare extracted files with CHECKSUMS.txt. A mismatch indicates corruption or modification, so download a fresh package before editing with it.', ['verify', 'sha256', 'integrity']],
                ['Why does my editor reject the 65-point file?', 'The application may limit lattice size or parse a smaller CUBE subset. Use the delivered 33-point or 17-point version and consult the host’s current LUT specification.', ['reject 65', 'limit', 'parser']],
                ['Why is the LUT list blank after installation?', 'The file may be in the wrong folder, still inside the ZIP, or hidden by an application cache. Extract it, confirm the extension, refresh the list, and restart the editor.', ['blank list', 'cache', 'folder']],
                ['Why does the exported result differ from the editor preview?', 'Export color space, range, codec, metadata, player color management, and display settings can differ from the timeline. Inspect the export back inside a controlled application and compare scopes.', ['export differs', 'player', 'metadata']],
                ['Why does the before-and-after tester stay in processing?', 'The queued image may still be running or a worker may be temporarily unavailable. Refresh after a short interval; if it expires or fails, retry with a smaller supported image.', ['processing', 'queue', 'tester']],
                ['What should I do before contacting technical support?', 'Record the product, CUBE size, application version, operating system, color space, exact error, and steps already tried. Remove confidential media and never send passwords.', ['technical support', 'diagnostics', 'details']],
            ]),
            $this->section('privacy-and-security', 'Privacy and security', 'Account protection, private files, uploaded photos, receipts, and responsible support.', [
                ['How are purchased package files stored?', 'Catalog releases are stored on private storage and resolved through server-side entitlement checks. Public product responses never include the private disk path or internal storage URL.', ['private storage', 'package', 'path']],
                ['How are uploaded tester photos protected?', 'Uploads use randomized private paths, owner authorization, verified accounts, temporary signed preview URLs, watermarks, expiration metadata, and cleanup controls.', ['upload privacy', 'signed url', 'owner']],
                ['Can support staff ask for my password?', 'No. Never share your password, recovery code, complete payment credentials, or session token. Legitimate troubleshooting can use account email, product, order time, and visible errors.', ['password', 'support', 'phishing']],
                ['What should I do if I suspect account misuse?', 'Change your password, sign out of untrusted devices when controls are available, secure the connected email account, and contact support with the approximate time and activity observed.', ['account misuse', 'password', 'report']],
                ['Does the site expose PayPal secrets to the browser?', 'No. Server credentials, webhook identifiers, and merchant validation data remain server-side. The browser receives only public configuration required to render checkout.', ['paypal secret', 'browser', 'server']],
                ['Why are download URLs access-controlled?', 'Access control protects licensed files and ensures the requesting user owns an active entitlement tied to a completed or valid free order.', ['download security', 'entitlement', 'owner']],
                ['Are payment and download events recorded?', 'The application records necessary order, payment, entitlement, webhook, and download status information for fulfillment, security, support, and audit purposes under the applicable policies.', ['records', 'audit', 'events']],
                ['Can I request deletion of a temporary photo test?', 'Yes. The tester provides a delete action for the owning account, and expiration cleanup also removes temporary files. Applicable account and transaction records follow the privacy and legal policies.', ['delete test', 'temporary', 'privacy']],
                ['Where can I read the privacy policy?', 'Use the Privacy link in the site footer. It describes the current handling of account, transaction, security, and service data more authoritatively than a support message.', ['privacy policy', 'footer', 'data']],
                ['How do I report a security concern safely?', 'Email goleaf@gmail.com with a concise description, affected URL, time, and reproducible steps. Do not access other users’ data, publish secrets, or attach malicious payloads.', ['security report', 'email', 'responsible']],
            ]),
            $this->section('refunds-and-remedies', 'Refunds and remedies', 'Digital-delivery consent, duplicate charges, defective files, and legally required remedies.', [
                ['Where can I find the current refund policy?', 'Open the Refund Policy from the footer or checkout legal panel before paying. The version accepted during checkout is recorded with the order for later reference.', ['refund policy', 'legal', 'version']],
                ['Are downloaded digital LUT purchases refundable?', 'Eligibility depends on the Refund Policy accepted at checkout and any mandatory consumer rights that apply. Review that policy before consenting to immediate digital delivery.', ['digital goods', 'refund', 'download']],
                ['What does immediate digital-delivery consent mean?', 'It asks you to acknowledge that fulfillment can begin after successful payment instead of waiting for a cooling-off period. Any rights that cannot legally be waived still apply.', ['digital delivery', 'consent', 'cooling off']],
                ['What should I do if I was charged twice?', 'Do not open additional checkout sessions. Send support both PayPal transaction references, the account email, product name, and approximate times so the records can be compared safely.', ['duplicate charge', 'paypal', 'transaction']],
                ['What if the ZIP is corrupt or incomplete?', 'Download the package again from My LUTs and compare its files with CHECKSUMS.txt. If a fresh download still fails, report the product and error so a replacement or other remedy can be assessed.', ['corrupt zip', 'replacement', 'checksum']],
                ['What if the delivered LUT differs from its product release?', 'Keep the original ZIP, manifest, and a non-confidential screenshot of the issue. Support can verify the content-addressed release and determine the appropriate correction or remedy.', ['wrong product', 'release', 'remedy']],
                ['Can I request a refund because I changed my mind?', 'Change-of-mind eligibility depends on the accepted Refund Policy, delivery state, and applicable law. The product preview and Try on Your Photo are provided to support an informed choice.', ['change mind', 'eligibility', 'preview']],
                ['How do PayPal refunds affect download access?', 'A confirmed full refund can revoke the related entitlement, while partial or disputed payment events may place the order under review. Keep the PayPal and site order references together.', ['paypal refund', 'entitlement', 'revoked']],
                ['How long does a refund review take?', 'No fixed review time is promised because verification and PayPal processing vary. A complete request with order details and evidence reduces avoidable correspondence and delay.', ['review time', 'support', 'evidence']],
                ['What information is safe to send with a refund request?', 'Send the account email, order or PayPal reference, product name, purchase time, and concise reason. Never send a password, complete card number, recovery code, or the licensed package.', ['refund request', 'safe details', 'security']],
            ]),
            $this->section('custom-lut-wizard', 'Custom LUT wizard', 'Projects, reference photos, controls, previews, builds, purchases, and generated packages.', [
                ['What is the Custom LUT wizard?', 'It is a guided tool for shaping a personal LUT from adjustable color parameters and private reference images. It is separate from buying a ready-made catalog product.', ['custom lut', 'wizard', 'personal']],
                ['Do I need an account to create a Custom LUT?', 'Yes. An account associates private uploads, drafts, generated previews, package builds, checkout records, and later downloads with the correct owner.', ['custom account', 'draft', 'owner']],
                ['Can I upload more than one reference photo?', 'Use the limits shown by the wizard for the current project. Choose representative images with varied tones so the look is not judged only against one unusually easy scene.', ['reference photos', 'upload', 'limits']],
                ['Do my reference photos become public examples?', 'No. Custom LUT photos and previews are private by default and are processed only to provide the requested tool, subject to the current privacy and retention policies.', ['custom privacy', 'public', 'reference']],
                ['Can I change a Custom LUT after generating previews?', 'You can continue adjusting an editable draft and generate updated previews within the tool’s limits. A purchased immutable build remains tied to the exact settings captured for that order.', ['custom edit', 'preview', 'immutable']],
                ['How should I evaluate a Custom LUT preview?', 'Check neutral objects, skin, foliage, saturated colors, highlights, and deep shadows across several reference images. Reduce extreme settings that work on one photo but fail elsewhere.', ['evaluate', 'custom preview', 'reference']],
                ['What files are included in a purchased Custom LUT package?', 'A completed build provides the package contents shown at checkout, including supported CUBE lattice sizes and release documentation generated for that immutable build.', ['custom package', 'cube', 'build']],
                ['Why is Custom LUT purchasing unavailable?', 'Commerce remains fail-closed when payment readiness, pricing, legal versions, build generation, or the selected project state is incomplete. Preserve the draft and retry after availability changes.', ['custom checkout', 'unavailable', 'readiness']],
                ['Where do purchased Custom LUTs appear?', 'Completed Custom LUT entitlements appear in the dedicated Purchased Custom LUTs account area, separate from drafts and from the ready-made catalog library.', ['purchased custom', 'account', 'downloads']],
                ['Can support design a Custom LUT on my behalf?', 'The self-service wizard and technical support do not automatically include bespoke grading or consultation. Any hands-on creative service would require a separate written agreement.', ['bespoke', 'consulting', 'support scope']],
            ]),
            $this->section('browser-and-accessibility', 'Browser and accessibility', 'Supported browser behavior, keyboard use, screen readers, uploads, motion, zoom, and reporting barriers.', [
                ['Which browser should I use?', 'Use a current standards-based browser with JavaScript, cookies, secure connections, and modern upload support enabled. Older browsers may not support checkout or image comparison controls.', ['browser', 'support', 'javascript']],
                ['Can I browse the catalog with a keyboard?', 'Navigation, links, buttons, FAQ disclosure controls, and form inputs are designed for keyboard operation. Use Tab and Shift+Tab to move, then Enter or Space to activate controls.', ['keyboard', 'tab', 'navigation']],
                ['Can a screen reader use the FAQ page?', 'The FAQ uses real headings, links, search labeling, native disclosure elements, and result status text so modern screen readers can navigate topics and expanded answers.', ['screen reader', 'faq', 'headings']],
                ['Does the site support browser zoom?', 'Responsive layouts are designed to reflow at common zoom levels, although very large previews or third-party payment surfaces may require additional scrolling on small screens.', ['zoom', 'reflow', 'responsive']],
                ['Can I reduce animation or motion?', 'The interface follows reduced-motion preferences where motion is used. Your browser or operating-system accessibility setting should be enabled before opening animated or transition-heavy controls.', ['reduced motion', 'animation', 'preference']],
                ['Why is the photo upload control not opening?', 'Check browser permissions, disable extensions that block file dialogs, and try a supported local JPEG, PNG, or WebP file. Private or managed devices may impose additional restrictions.', ['upload control', 'browser permission', 'extension']],
                ['Why does the before-and-after comparison not move?', 'Wait until processing finishes, then try pointer, touch, or keyboard interaction supported by the displayed control. Refresh once if cached page state no longer matches the job status.', ['comparison', 'slider', 'processing']],
                ['Can I complete PayPal checkout with assistive technology?', 'The site labels its checkout controls, while the PayPal approval surface is provided by PayPal. Use a current browser and report whether a barrier occurs on this site or inside PayPal.', ['paypal accessibility', 'assistive technology', 'checkout']],
                ['Does high-contrast mode affect LUT previews?', 'High-contrast or forced-color modes may alter interface chrome but cannot accurately represent creative image color. Evaluate LUT imagery with a normal calibrated display mode when possible.', ['high contrast', 'forced colors', 'preview']],
                ['How do I report an accessibility problem?', 'Email goleaf@gmail.com with the page, task, browser, assistive technology, and exact barrier. Do not include passwords, private photos, or unnecessary payment information.', ['accessibility report', 'barrier', 'email']],
            ]),
            $this->section('updates-and-support', 'Updates and support', 'Release identity, backups, product changes, response details, and long-term use.', [
                ['How can I identify my exact LUT release?', 'The customer README and manifest include the product name, parameter hash, and release fingerprint. Keep these files with the CUBE files when requesting support.', ['release', 'fingerprint', 'identify']],
                ['Will a product always keep the same color transform?', 'A published release is content-addressed and retained for entitlement integrity. Future product updates should use a new release rather than silently changing a purchased package.', ['update', 'immutable', 'version']],
                ['What happens if a newer release becomes current?', 'New purchases and tests use the current ready release, while existing order records retain their purchased version and file reference for reproducible downloads.', ['new release', 'current', 'existing order']],
                ['Are package files checked before release?', 'The release pipeline validates the 17, 33, and 65 CUBE structure, checks the transform samples, tests Cube33 with FFmpeg, validates ZIP entries, and records size and SHA-256 metadata.', ['validation', 'ffmpeg', 'release']],
                ['Can support recreate a deleted local copy?', 'If your entitlement remains active and the release is available, download the original package again from My LUTs. Support cannot recover unrelated local edits or project files.', ['recover', 'deleted', 'redownload']],
                ['Do application updates affect installed LUTs?', 'They can change import locations, color management, interpolation, or cache behavior. Keep the original package and recheck a representative project after major editor updates.', ['application update', 'compatibility', 'recheck']],
                ['How quickly will support reply?', 'Response time is not guaranteed and varies with volume and issue complexity. A complete first message with product, application, system, and error details reduces avoidable follow-up.', ['response time', 'support', 'reply']],
                ['Can support grade my project for me?', 'Standard product support covers package delivery, installation, and reproducible technical issues. Custom grading, consulting, and project review require separate agreement if offered.', ['custom grading', 'consulting', 'scope']],
                ['What if my question is not listed here?', 'Search with the product, application, or error term, then email goleaf@gmail.com if no answer fits. Include enough context to distinguish installation, color, checkout, or account issues.', ['not listed', 'search', 'contact']],
                ['How should I preserve LUTs for long-term projects?', 'Archive the original ZIP, manifest, checksums, accepted license record, and application project settings in redundant storage. Test restores periodically instead of assuming a backup is readable.', ['archive', 'long term', 'backup']],
            ]),
        ];
    }

    /**
     * @param  list<array{0: string, 1: string, 2: list<string>}>  $items
     * @return array{
     *     slug: string,
     *     title: string,
     *     description: string,
     *     items: list<array{id: string, question: string, answer: string, keywords: list<string>}>
     * }
     */
    private function section(string $slug, string $title, string $description, array $items): array
    {
        return [
            'slug' => $slug,
            'title' => $title,
            'description' => $description,
            'items' => array_map(static fn (array $item): array => [
                'id' => $slug.'-'.Str::slug($item[0]),
                'question' => $item[0],
                'answer' => $item[1],
                'keywords' => $item[2],
            ], $items),
        ];
    }
}
