<?php

return [
    'enabled' => (bool) env('LUT_WIZARD_ENABLED', true),
    'transform_version' => env('LUT_WIZARD_TRANSFORM_VERSION', 'lut_transform_v1'),
    'maximum_active_projects' => (int) env('LUT_WIZARD_MAX_PROJECTS', 10),
    'project_expiration_days' => (int) env('LUT_WIZARD_PROJECT_TTL_DAYS', 30),
    'maximum_photos_per_project' => (int) env('LUT_WIZARD_MAX_PHOTOS', 3),
    'photo_expiration_minutes' => (int) env('LUT_WIZARD_PHOTO_TTL_MINUTES', 60),
    'disk' => env('LUT_TESTER_PRIVATE_DISK', 'private'),
    'prefix' => 'custom-lut-projects',
    'work_prefix' => 'custom-lut-work',
    'queue_name' => env('LUT_TESTER_QUEUE', 'images'),
    'preview_lut_size' => (int) env('LUT_WIZARD_PREVIEW_LUT_SIZE', 33),
    'cpu_fallback_maximum_edge' => (int) env('LUT_WIZARD_CPU_FALLBACK_MAX_EDGE', 1024),
    'autosave_debounce_ms' => (int) env('LUT_WIZARD_AUTOSAVE_DEBOUNCE_MS', 800),
    'maximum_local_undo_entries' => (int) env('LUT_WIZARD_UNDO_HISTORY', 50),
    'variation_count' => (int) env('LUT_WIZARD_VARIATION_COUNT', 4),
    'variation_daily_limit' => (int) env('LUT_WIZARD_VARIATION_DAILY_LIMIT', 20),
    'variation_per_minute_limit' => (int) env('LUT_WIZARD_VARIATION_PER_MINUTE_LIMIT', 5),
    'project_mutation_rate_limit' => (int) env('LUT_WIZARD_MUTATIONS_PER_MINUTE', 120),
    'project_creation_rate_limit' => (int) env('LUT_WIZARD_CREATIONS_PER_MINUTE', 5),
    'photo_upload_rate_limit' => (int) env('LUT_WIZARD_PHOTO_UPLOADS_PER_MINUTE', 5),
    'duplicate_rate_limit' => (int) env('LUT_WIZARD_DUPLICATES_PER_MINUTE', 10),
    'private_preview_rate_limit' => (int) env('LUT_WIZARD_PREVIEW_REQUESTS_PER_MINUTE', 180),
    'signed_preview_url_lifetime' => (int) env('LUT_WIZARD_SIGNED_PREVIEW_URL_MINUTES', 10),
    'prune_batch_size' => (int) env('LUT_WIZARD_PRUNE_BATCH_SIZE', 500),
    'upload' => [
        'max_upload_mb' => (int) env('LUT_TESTER_MAX_UPLOAD_MB', 20),
        'max_pixels' => (int) env('LUT_TESTER_MAX_PIXELS', 50_000_000),
        'max_input_edge' => (int) env('LUT_TESTER_MAX_INPUT_EDGE', 12_000),
        'min_width' => (int) env('LUT_TESTER_MIN_WIDTH', 320),
        'min_height' => (int) env('LUT_TESTER_MIN_HEIGHT', 320),
        'preview_max_edge' => (int) env('LUT_TESTER_PREVIEW_MAX_EDGE', 1_920),
        'preview_quality' => (int) env('LUT_TESTER_PREVIEW_QUALITY', 82),
        'image_driver' => env('IMAGE_DRIVER', 'gd'),
        'transparency_background' => env('LUT_TESTER_TRANSPARENCY_BACKGROUND', '#ffffff'),
    ],
];
