<?php

return [
    'enabled' => (bool) env('LUT_TESTER_ENABLED', true),
    'disk' => env('LUT_TESTER_PRIVATE_DISK', 'private'),
    'prefix' => 'lut-tests',
    'work_prefix' => 'lut-tests-work',
    'ffmpeg_binary' => env('LUT_TESTER_FFMPEG_BINARY', 'ffmpeg'),
    'ffmpeg_timeout' => (int) env('LUT_TESTER_FFMPEG_TIMEOUT', 45),
    'process_idle_timeout' => (int) env('LUT_TESTER_PROCESS_IDLE_TIMEOUT', 20),
    'queue' => env('LUT_TESTER_QUEUE', 'images'),
    'max_upload_mb' => (int) env('LUT_TESTER_MAX_UPLOAD_MB', 20),
    'max_pixels' => (int) env('LUT_TESTER_MAX_PIXELS', 50_000_000),
    'max_input_edge' => (int) env('LUT_TESTER_MAX_INPUT_EDGE', 12_000),
    'min_width' => (int) env('LUT_TESTER_MIN_WIDTH', 320),
    'min_height' => (int) env('LUT_TESTER_MIN_HEIGHT', 320),
    'preview_max_edge' => (int) env('LUT_TESTER_PREVIEW_MAX_EDGE', 1_920),
    'preview_format' => 'webp',
    'preview_quality' => (int) env('LUT_TESTER_PREVIEW_QUALITY', 82),
    'expires_minutes' => (int) env('LUT_TESTER_EXPIRES_MINUTES', 60),
    'max_active_tests_per_user' => (int) env('LUT_TESTER_MAX_ACTIVE_TESTS_PER_USER', 3),
    'upload_rate_limits' => [
        'per_minute' => (int) env('LUT_TESTER_UPLOADS_PER_MINUTE', 5),
        'per_day' => (int) env('LUT_TESTER_UPLOADS_PER_DAY', 30),
    ],
    'watermark_text' => env('LUT_TESTER_WATERMARK_TEXT', 'LUT WEB PREVIEW'),
    'watermark_opacity' => (float) env('LUT_TESTER_WATERMARK_OPACITY', 0.34),
    'watermark_pattern_opacity' => (float) env('LUT_TESTER_WATERMARK_PATTERN_OPACITY', 0.16),
    'watermark_spacing' => (int) env('LUT_TESTER_WATERMARK_SPACING', 360),
    'transparency_background' => env('LUT_TESTER_TRANSPARENCY_BACKGROUND', '#ffffff'),
    'max_cube_size_bytes' => (int) env('LUT_TESTER_MAX_CUBE_SIZE_BYTES', 20 * 1024 * 1024),
    'max_cube_line_length' => (int) env('LUT_TESTER_MAX_CUBE_LINE_LENGTH', 8_192),
    'max_cube_absolute_channel_value' => (float) env('LUT_TESTER_MAX_CUBE_ABSOLUTE_CHANNEL_VALUE', 64.0),
    'interpolation' => env('LUT_TESTER_INTERPOLATION', 'tetrahedral'),
    'image_driver' => env('IMAGE_DRIVER', 'gd'),
];
